seed: 1000

data:
  seed: 1000
  domain: [0, 6.283185307] # domain of x values
  omegas: 6 # number of frequencies in each dimension
  offset: False
  coefficients_max: 1.0
  coefficients_min: 0.0
  batch_size: -1
  zero_centered: True

model:
  seed: 1000
  n_qubits: 6
  n_layers: 1
  circuit_type: "Circuit_19" # Hardware_Efficient Circuit_15 Circuit_17 Circuit_19
  data_reupload: True
  encoding_gates: ["RY"]
  encoding_strategy: "standard"
  output_qubit: -1
  initialization: "random"
  initialization_domain: [0, 6.283185307179586]
  noise_params:
    BitFlip: 0.0
    PhaseFlip: 0.0
    AmplitudeDamping: 0.0
    PhaseDamping: 0.0
    Depolarizing: 0.0
  mp_threshold: -1

train:
  steps: 1000
  learning_rate: 0.005
  batch_size: -1
  loss_functions: ["mse"]
  loss_scalers: [1.0]

fcc:
  seed: 1000
  n_samples: 500
