seed: 1000

data:
  seed: 1000
  domain: [0, 6.283185307] # domain of x values
  coefficients_max: 1.0
  coefficients_min: 0.0
  batch_size: -1
  zero_centered: True

model:
  seed: 1000
  n_qubits: 3
  n_layers: 1
  circuit_type: "Circuit_17" # Hardware_Efficient Circuit_15 Circuit_17 Circuit_19
  data_reupload: True
  encoding_gates: ["RY"]
  output_qubit: -1
  initialization: "random"
  initialization_domain: [0, 6.283185307179586]

train:
  steps: 1000
  learning_rate: 5e-3
  batch_size: -1
  loss_functions: ["mse"]
  loss_scalers: [1.0]

fcc:
  seed: 1000
  n_samples: 500
  sample_axis: ["unitary", "pulse"]
  pulse_params_variance: 1e-3
  method: "pearson"
  weighting: False
  scale: True
  numerical_cap: 1e-10

fidelity:
  seed: 1000
  n_samples: 500
  pulse_params_variance: 1e-3
  scale: True

expressibility:
  seed: 1000
  n_samples: 500
  n_bins: 50
  pulse_params_variance: 1e-3
  scale: True
